# Generated by Django 4.2.26 on 2025-11-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0008_doctor_visitador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescripcion',
            name='ms_trim',
            field=models.FloatField(blank=True, null=True, verbose_name='Market Share Trimestral'),
        ),
        migrations.AlterField(
            model_name='prescripcion',
            name='rank_trim',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ranking Trimestral'),
        ),
    ]
