# Generated by Django 4.2.29 on 2026-03-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0006_visita_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='se_genero_pedido',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
